#!/usr/bin/env bash
# Production bootstrap: deploy the stack to a Linux server reachable at
# https://$DOMAIN and automate the first-run admin + team creation.
#
# Safe to re-run. Does NOT destroy data under any flag — no --reset here.
#
# Prereqs (things this script does NOT do for you):
#   - Docker + Docker Compose v2 installed
#   - Ports 80/443 reachable from the public internet
#   - DNS A record for $DOMAIN points at this server (Caddy needs this
#     before first boot to get a Let's Encrypt cert)
#   - .env filled in: DOMAIN, ACME_EMAIL, POSTGRES_PASSWORD, SITE_NAME
#
# What it does:
#   1. Validates .env and preflight checks DNS + public IP match.
#   2. docker compose up -d --build (postgres + mattermost-branded + caddy).
#   3. Waits for Caddy to issue a TLS cert + Mattermost API to respond.
#   4. Creates the admin user (or logs in if one already exists) and a team.
#
# Env overrides (defaults shown):
#   ADMIN_EMAIL=$ACME_EMAIL
#   ADMIN_USERNAME=admin
#   ADMIN_PASSWORD=<auto-generated, printed to stdout>
#   TEAM_NAME=relay
#   TEAM_DISPLAY=$SITE_NAME
#
# Flags:
#   --skip-dns-check   Don't verify DNS points at this box (useful behind NATs
#                      with split-horizon DNS or when running from the box itself)
#   --no-bootstrap     Just boot the stack; skip admin/team creation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

log()  { printf "==> %s\n" "$*"; }
ok()   { printf " ok  %s\n" "$*"; }
warn() { printf "  !  %s\n" "$*" >&2; }
die()  { printf "  x  %s\n" "$*" >&2; exit 1; }

SKIP_DNS=0
NO_BOOTSTRAP=0
for arg in "$@"; do
  case "$arg" in
    --skip-dns-check) SKIP_DNS=1 ;;
    --no-bootstrap)   NO_BOOTSTRAP=1 ;;
    -h|--help) sed -n '2,33p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $arg (try --help)" ;;
  esac
done

# --- preflight --------------------------------------------------------------
for bin in curl jq docker openssl; do
  command -v "$bin" >/dev/null 2>&1 || die "missing required binary: $bin"
done
docker compose version >/dev/null 2>&1 || die "docker compose v2 not available"

[[ -f ./docker-compose.yml ]] || die "docker-compose.yml not found — run from the project root"
[[ -f ./.env ]] || die ".env not found — copy .env.example to .env and fill it in"

# Load .env into the environment so the rest of this script can read it.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

for var in DOMAIN ACME_EMAIL POSTGRES_PASSWORD SITE_NAME; do
  [[ -n "${!var:-}" ]] || die "$var is not set in .env"
done

# Defaults for values not in .env
ADMIN_EMAIL=${ADMIN_EMAIL:-$ACME_EMAIL}
ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
TEAM_NAME=${TEAM_NAME:-relay}
TEAM_DISPLAY=${TEAM_DISPLAY:-$SITE_NAME}

GENERATED_PASSWORD=0
if [[ -z "${ADMIN_PASSWORD:-}" ]]; then
  # 24 random bytes → ~32 base64 chars. Strip + and / to keep it shell-safe.
  ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '+/=')
  GENERATED_PASSWORD=1
fi

MM_URL="https://$DOMAIN"

# --- DNS + public IP sanity check ------------------------------------------
if [[ "$SKIP_DNS" -eq 0 ]]; then
  log "Preflight: checking DNS for $DOMAIN"

  resolved=""
  if command -v dig >/dev/null 2>&1; then
    resolved=$(dig +short "$DOMAIN" | grep -E '^[0-9.]+$' | tail -n1 || true)
  elif command -v getent >/dev/null 2>&1; then
    resolved=$(getent hosts "$DOMAIN" | awk '{print $1}' | head -n1 || true)
  fi

  if [[ -z "$resolved" ]]; then
    die "$DOMAIN does not resolve. Point an A record at this server before running. (--skip-dns-check to override)"
  fi

  # What does the public internet see as our IP?
  public_ip=$(curl -sS --max-time 5 https://api.ipify.org || true)
  if [[ -n "$public_ip" && "$resolved" != "$public_ip" ]]; then
    warn "$DOMAIN resolves to $resolved, but this server's public IP is $public_ip."
    warn "Caddy will fail to issue a Let's Encrypt cert unless DNS points here."
    warn "Re-run with --skip-dns-check if you've verified DNS is correct (split-horizon, proxy, etc)."
    die "aborting — fix DNS or use --skip-dns-check"
  fi

  ok "DNS resolves to $resolved"
fi

compose() { docker compose "$@"; }

# --- phase 1: build + boot stack --------------------------------------------
log "Building branded image + starting postgres, mattermost, caddy"
compose up -d --build

# --- phase 2: wait for TLS + Mattermost API --------------------------------
# First-time Let's Encrypt issuance can take 30-60s after Caddy starts.
# Give it up to 5 minutes before giving up.
log "Waiting for $MM_URL/api/v4/system/ping (up to 5 min — first-run Let's Encrypt cert issuance)"
for i in $(seq 1 300); do
  if curl -fsS --max-time 3 "$MM_URL/api/v4/system/ping" >/dev/null 2>&1; then
    ok "Stack is up at $MM_URL (after ${i}s)"
    break
  fi
  if [[ "$i" -eq 300 ]]; then
    warn "Timed out waiting for $MM_URL. Recent logs:"
    compose logs --tail=50 caddy mattermost >&2
    die "giving up — check Caddy cert issuance and DNS"
  fi
  sleep 1
done

if [[ "$NO_BOOTSTRAP" -eq 1 ]]; then
  cat <<EOF

Stack is up at $MM_URL — bootstrap skipped (--no-bootstrap).
Visit $MM_URL to create the first account manually.
EOF
  exit 0
fi

# --- phase 3: admin login / create -----------------------------------------
# Login-first: once any user exists, Mattermost blocks public user creation
# (EnableOpenServer=false by default), so we can't tell "first run" from
# "already initialized" via create alone.
login_body=$(jq -n --arg u "$ADMIN_USERNAME" --arg p "$ADMIN_PASSWORD" \
  '{login_id:$u, password:$p}')

attempt_login() {
  curl -sS -D /tmp/mm-login.headers -o /tmp/mm-login.json -w "%{http_code}" \
    -H "Content-Type: application/json" \
    -d "$login_body" \
    "$MM_URL/api/v4/users/login"
}

log "Logging in as '$ADMIN_USERNAME'"
login_status=$(attempt_login)

if [[ "$login_status" == "401" ]]; then
  if [[ "$GENERATED_PASSWORD" -eq 0 ]]; then
    warn "Login failed with supplied ADMIN_PASSWORD. Assuming first run."
  fi
  log "Creating admin user '$ADMIN_USERNAME' ($ADMIN_EMAIL)"
  create_body=$(jq -n --arg e "$ADMIN_EMAIL" --arg u "$ADMIN_USERNAME" --arg p "$ADMIN_PASSWORD" \
    '{email:$e, username:$u, password:$p}')
  create_status=$(curl -sS -o /tmp/mm-create.json -w "%{http_code}" \
    -H "Content-Type: application/json" \
    -d "$create_body" \
    "$MM_URL/api/v4/users")
  if [[ "$create_status" != "201" ]]; then
    cat /tmp/mm-create.json >&2
    die "failed to create admin (HTTP $create_status) — if an admin already exists, pass ADMIN_PASSWORD=<the real password>"
  fi
  ok "Admin user created"
  login_status=$(attempt_login)
fi

if [[ "$login_status" != "200" ]]; then
  cat /tmp/mm-login.json >&2
  die "login failed (HTTP $login_status) — check ADMIN_USERNAME / ADMIN_PASSWORD"
fi

ADMIN_TOKEN=$(awk 'tolower($1)=="token:" {print $2}' /tmp/mm-login.headers | tr -d '\r\n')
[[ -n "$ADMIN_TOKEN" ]] || { cat /tmp/mm-login.json >&2; die "login did not return a Token header"; }
ADMIN_USER_ID=$(jq -r '.id' </tmp/mm-login.json)
ok "Logged in (user_id=$ADMIN_USER_ID)"

auth=(-H "Authorization: Bearer $ADMIN_TOKEN")

# --- phase 4: team ---------------------------------------------------------
log "Ensuring team '$TEAM_NAME' exists"
team_status=$(curl -sS "${auth[@]}" -o /tmp/mm-team.json -w "%{http_code}" \
  "$MM_URL/api/v4/teams/name/$TEAM_NAME")
case "$team_status" in
  200)
    TEAM_ID=$(jq -r '.id' </tmp/mm-team.json)
    ok "Team already exists (id=$TEAM_ID)"
    ;;
  404)
    team_body=$(jq -n --arg n "$TEAM_NAME" --arg d "$TEAM_DISPLAY" \
      '{name:$n, display_name:$d, type:"O"}')
    create_team_status=$(curl -sS "${auth[@]}" -o /tmp/mm-team.json -w "%{http_code}" \
      -H "Content-Type: application/json" \
      -d "$team_body" "$MM_URL/api/v4/teams")
    [[ "$create_team_status" == "201" ]] || { cat /tmp/mm-team.json >&2; die "failed to create team (HTTP $create_team_status)"; }
    TEAM_ID=$(jq -r '.id' </tmp/mm-team.json)
    ok "Team created (id=$TEAM_ID)"
    ;;
  *)
    cat /tmp/mm-team.json >&2
    die "unexpected response looking up team (HTTP $team_status)"
    ;;
esac

# Idempotent: first call returns 201, subsequent calls return 4xx. Either way fine.
member_body=$(jq -n --arg t "$TEAM_ID" --arg u "$ADMIN_USER_ID" \
  '{team_id:$t, user_id:$u}')
curl -sS "${auth[@]}" -H "Content-Type: application/json" \
  -d "$member_body" \
  "$MM_URL/api/v4/teams/$TEAM_ID/members" >/dev/null || true

# --- done -------------------------------------------------------------------
cat <<EOF

Production setup complete.

  Site:         $MM_URL
  Site name:    $SITE_NAME
  Team:         $TEAM_NAME
  Admin login:  $ADMIN_USERNAME / $ADMIN_PASSWORD
$( [[ "$GENERATED_PASSWORD" -eq 1 ]] && printf "  (password auto-generated — save it now; re-running won't show it again)\n" )

Next steps:
  - Log in at $MM_URL and change the admin password if you want something memorable.
  - Main Menu → Invite People → generate an invite link for your friends.
  - Set up backups: SETUP.md has the nightly pg_dump cron recipe.

Tail logs:    docker compose logs -f
Upgrade:      docker compose pull && docker compose up -d --build
EOF
